syntax = "LuaJIT"
column_width = 110
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "None"
collapse_simple_statement = "ConditionalOnly"
space_after_function_names = "Definitions"
block_newline_gaps = "Never"
